### ISSUE TITLE
Roadmap to going public

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/JuliaBUGS.jl#11]
- [x] Rename ./BugsModels.jl -> SymbolicPPL.jl
- [x] Move AbstractPPL.GraphPPL here
- [x] Think about how to manage BUGS examples (submodule? common interface to query like https://github.com/TuringLang/DynamicPPL.jl/blob/master/src/test_utils.jl)
- [x] #12
- [x] "Work in progress" warning
- [x] Merge #10
- [x] Document existing stuff
- [x] Check licensing of example models
- [x] CI and doc host
