### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by sunxd3** [TuringLang/JuliaBUGS.jl#14]
- [x] Improve and include the tutorial written for GSoC submission
- [ ] Add a walkthrough example: define model -> using `bugsast` and `bugsmodel` -> compile to graph representation -> inference and results
- [ ] API can be added gradually
